resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

ghc-options:
  node-editor: -DGHCJS_BROWSER
  text-editor: -DGHCJS_BROWSER
extra-deps:
  - cond-0.4.1.1
  - datetime-0.3.1
  - ghcjs-dom-0.7.0.4
  - ghcjs-dom-jsffi-0.7.0.4
  - zlib-0.6.1.2

packages:
- {location: ./node-editor}
- {location: ./text-editor}
- {extra-dep: true, location: ./lib}
- {extra-dep: true, location: ../libs/luna-studio-common}
- {extra-dep: true, location: ../libs/scope-searcher}
- extra-dep: true
  location: {commit: 4d4914483e7f207c94fcadf8f7f2736367165451, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: 2371dec86a94f2e50ad8bdb8cad4e9afa2a9291a, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: fb0e46aacaa7060046f88d4c5a5f708fd443c8ae, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 62aebd5ecb6ea873ce8db4cc230d156126cd82ee, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: adb894846d34ceaa005961bd8fe676023cf1b036, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: c20f35c8e2f25fd84df385e8646b125d9fca8ac4, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 0f86d4dff7192db7b4f4001f427126a889ff311f, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: 896f4472b64ab23e610db74991de0af3b1ec0e17, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 7a0eb39c82acb212a50c028143458ae7ce93745c, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: 7917cc1d84e421823b6291bb4c5ec065a29e9c42, git: 'https://github.com/luna/hsprocessing.git'}
- extra-dep: true
  location: {commit: 5dc5b731a4313e44d55677ed6b9f38456feb2d56, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: 3bd224d169262af9f473e9b1bd691fd12caec8e2, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: f761757fa3204ec780031835099ef6d48020ba8f, git: 'https://github.com/luna/luna.git'}
  subdirs: [syntax/text/lexer]
- extra-dep: true
  location: {commit: ffd97a6ec0eab065cebf06663a37362c1e13a05b, git: 'https://github.com/luna/monoid'}
- extra-dep: true
  location: {commit: 23d11542f1c58bd56feeed9c799c5f6b705b11fd, git: 'https://github.com/luna/parsert'}
- extra-dep: true
  location: {commit: 64179d2492e68016fb34d09b6faf966f3b9f91bd, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: ad94b1f2e4bc87b81853ff746b64c59b3eae7f09, git: 'https://github.com/luna/react-flux'}
- extra-dep: true
  location: {commit: e8dfa519660ae1174e7e28ae7d74f85955bfa415, git: 'https://github.com/luna/text-processing.git'}
- extra-dep: true
  location: {commit: d5c2a68df9b34b8370c98a84f8bcaf311869daa9, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: cf0899b87e026c4a424af05d714eec155d8f8ae9, git: 'https://github.com/luna/vector-text.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
