resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

ghc-options:
  node-editor: -DGHCJS_BROWSER
  text-editor: -DGHCJS_BROWSER
extra-deps:
  - cond-0.4.1.1
  - datetime-0.3.1
  - ghcjs-dom-0.7.0.4
  - ghcjs-dom-jsffi-0.7.0.4

packages:
  - location: ./node-editor
  - location: ./text-editor
  - location: ./lib
    extra-dep: true
  - location: ../libs/luna-studio-common
    extra-dep: true
  - location: ../libs/scope-searcher
    extra-dep: true
  - location:
      git: https://github.com/luna/container.git
      commit: 14540e932e14953b0eb5ebdea85045e8d261f023
    extra-dep: true
  - location:
      git:    https://github.com/luna/convert.git
      commit: 901b1491ddf84c309ba1e6a670d9a519e4c673b6
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-construction.git
      commit: fb0e46aacaa7060046f88d4c5a5f708fd443c8ae
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-layer.git
      commit: 62aebd5ecb6ea873ce8db4cc230d156126cd82ee
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-prop.git
      commit: adb894846d34ceaa005961bd8fe676023cf1b036
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-repr.git
      commit: c20f35c8e2f25fd84df385e8646b125d9fca8ac4
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-rtuple.git
      commit: 0f86d4dff7192db7b4f4001f427126a889ff311f
    extra-dep: true
  - location:
      git:    https://github.com/luna/functor-utils.git
      commit: 8a5a3c6c132b71eed041269c17182100ff98603f
    extra-dep: true
  - location:
      git: https://github.com/luna/hsprocessing.git
      commit: b96747cf0c3a4362b4d5827eb567be85c2d1dd13
    extra-dep: true
  - location:
      git:    https://github.com/luna/impossible.git
      commit: 5dc5b731a4313e44d55677ed6b9f38456feb2d56
    extra-dep: true
  - location:
      git:    https://github.com/luna/lens-utils.git
      commit: 944351bc0b972b21ae4c6a092c596edf96f13129
    extra-dep: true
  - location:
      git: https://github.com/luna/monoid
      commit: 7f5f64d1b1f81827431c9462d35665adbb609ba8
    extra-dep: true
  - location:
      git: https://github.com/luna/prologue.git
      commit: d46ca8c8e8333009c96b35e082f7bc2fda1f9ce3
    extra-dep: true
  - location:
      git: https://github.com/luna/react-flux
      commit: ad94b1f2e4bc87b81853ff746b64c59b3eae7f09
    extra-dep: true
  - location:
      git: https://github.com/luna/typelevel.git
      commit: 9165d1818d9ec0b0f030623282b80c2d654089ea
    extra-dep: true
  - location:
      git: https://github.com/luna/visualization-api.git
      commit: af5a618f5813ac639a6760836a6d6fa7ef5af1da
    extra-dep: true
