resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

ghc-options:
  node-editor: -DGHCJS_BROWSER
  text-editor: -DGHCJS_BROWSER
extra-deps:
  - cond-0.4.1.1
  - datetime-0.3.1
  - ghcjs-dom-0.7.0.4
  - ghcjs-dom-jsffi-0.7.0.4

packages:
- {location: ./node-editor}
- {location: ./text-editor}
- {extra-dep: true, location: ./lib}
- {extra-dep: true, location: ../libs/luna-studio-common}
- {extra-dep: true, location: ../libs/scope-searcher}
- extra-dep: true
  location: {commit: 14540e932e14953b0eb5ebdea85045e8d261f023, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: 93447d94a88d812b2df840eced3a7d3ec4d1e82d, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: fb0e46aacaa7060046f88d4c5a5f708fd443c8ae, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 62aebd5ecb6ea873ce8db4cc230d156126cd82ee, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: adb894846d34ceaa005961bd8fe676023cf1b036, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: c20f35c8e2f25fd84df385e8646b125d9fca8ac4, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 0f86d4dff7192db7b4f4001f427126a889ff311f, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: 409dc63cc1ccd2c85000460ce39df5c19dd15d0c, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: 7917cc1d84e421823b6291bb4c5ec065a29e9c42, git: 'https://github.com/luna/hsprocessing.git'}
- extra-dep: true
  location: {commit: 5dc5b731a4313e44d55677ed6b9f38456feb2d56, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: 4af8e1021a8127b05d98920e387150fa4f0aa2e4, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 7f5f64d1b1f81827431c9462d35665adbb609ba8, git: 'https://github.com/luna/monoid'}
- extra-dep: true
  location: {commit: 642b290e21d94b01273bfae05963b203f75c8191, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: ad94b1f2e4bc87b81853ff746b64c59b3eae7f09, git: 'https://github.com/luna/react-flux'}
- extra-dep: true
  location: {commit: 9165d1818d9ec0b0f030623282b80c2d654089ea, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
