name:                text-editor
version:             0.1.0.0
synopsis:            NodeLab
homepage:            www.nodelab.io
license:             AllRightsReserved
author:              New Byte Order
maintainer:          contact@nodelab.io

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - ScopedTypeVariables
  - TemplateHaskell

ghc-options:
    -Wall -O2

#
# ACHTUNG! Zmieniasz tu - zmien w interactive
#
dependencies:
  - "base >= 4.9 && < 4.10"
  - aeson
  - binary
  - bytestring
  - common
  - containers
  - datetime
  - ghcjs-base
  - ghcjs-prim
  - lens
  - luna-empire-api
  - luna-empire-api-json
  - mtl
  - prologue
  - random
  - scope-searcher
  - text
  - time
  - transformers
  - uuid-types



executables:
  text-editor:
    main:             Main.hs
    source-dirs:      src
