resolver: lts-12.26
ghc-options:
    $everything:
        -O1
        -Wall
        -Wno-name-shadowing
        -fexcess-precision
        -fexpose-all-unfoldings
        -flate-dmd-anal
        -fmax-worker-args=1000
        -fsimpl-tick-factor=400
        -fspec-constr-keen
        -fspecialise-aggressively
        -fstatic-argument-transformation
        -funbox-strict-fields
        -threaded
        -fomit-interface-pragmas
        -fconstraint-solver-iterations=100

local-bin-path:
  ../../dist/bin/private
apply-ghc-options: everything

# package-indices:
#   - name:            standard-hackage
#     download-prefix: https://hackage.haskell.org/package/
#     http: https://hackage.haskell.org/01-index.tar.gz

extra-deps:
- c-storable-deriving-0.1.3
- unagi-chan-0.4.1.0

allow-newer: true

packages:
- {extra-dep: false, location: ../../libs/luna-empire}
- {extra-dep: true, location: ../../libs/batch/plugins/luna-empire}
- {extra-dep: true, location: ../../libs/batch/plugins/request-monitor}
- {extra-dep: true, location: ../../libs/luna-studio-common}
- {extra-dep: true, location: ../../libs/m-logger}
- {extra-dep: true, location: ../../libs/ws-connector}
- {extra-dep: true, location: ../../libs/zmq-bus-config}
- {extra-dep: true, location: ../../libs/zmq-bus}
- {extra-dep: true, location: ../../libs/zmq-rpc}
- {location: ../../tools/batch/plugins/ws-connector}
- {location: ../../tools/batch/plugins/broker}
- {location: ../../libs/undo-redo}
- {location: ../../tools/batch/plugins/bus-logger}
- {location: ../../tools/batch/plugins/luna-empire}
- {location: ../../tools/batch/plugins/request-monitor}
- extra-dep: true
  location: {commit: 0aa5f8dffb60e3874346f382362e0754ca5d8511, git: 'https://github.com/luna/luna.git'}
  subdirs:
    - core
    - syntax/text/parser
    - syntax/text/builder
    - syntax/text/lexer
    - syntax/text/model
    - syntax/text/prettyprint
    - debug
    - passes
    - package
    - runtime
    - stdlib

    - lib/autovector
    - lib/ci
    - lib/code-builder
    - lib/container
    - lib/convert
    - lib/cpp-containers
    - lib/data-construction
    - lib/data-property
    - lib/data-storable
    - lib/data-tag
    - lib/data-typemap
    - lib/datafile
    - lib/exception
    - lib/foreign-utils
    - lib/functor-utils
    - lib/future
    - lib/generic-traversable
    - lib/generic-traversable2
    - lib/hspec-jenkins
    - lib/impossible
    - lib/layered-state
    - lib/layouting
    - lib/lens-utils
    - lib/memory-manager
    - lib/memory-pool
    - lib/monad-branch
    - lib/monoid
    - lib/nested-containers
    - lib/parser-utils
    - lib/prologue
    - lib/syntax-definition
    - lib/terminal-text
    - lib/text-processing
    - lib/th-builder
    - lib/tuple-utils
    - lib/type-cache
    - lib/typelevel
    - lib/vector-text
    - lib/yaml-utils

- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
- extra-dep: true
  location: {commit: 4c71b554d738021b51723dbec6d1f1c823e73579, git: 'https://github.com/TomMD/entropy.git'}
