resolver: lts-8.2
ghc-options:
  '*': -threaded -fconstraint-solver-iterations=100 -O2
local-bin-path:
  ../../dist/bin/private

extra-deps:
- aeson-1.1.1.0
- ansi-terminal-0.6.3.1
- cond-0.4.1.1
- containers-0.5.8.2
- error-util-0.0.1.1
- ghc-mtl-1.2.1.0
- ghc-session-0.1.2.0
- libffi-0.1
- path-0.6.1
- safe-exceptions-0.1.6.0
- shelly-1.6.8.4
- serialport-0.4.7
- uuid-1.3.13

packages:
- {extra-dep: false, location: ../../libs/luna-empire}
- {extra-dep: true, location: ../../libs/batch/plugins/luna-empire}
- {extra-dep: true, location: ../../libs/batch/plugins/request-monitor}
- {extra-dep: true, location: ../../libs/luna-studio-common}
- {extra-dep: true, location: ../../libs/m-logger}
- {extra-dep: true, location: ../../libs/ws-connector}
- {extra-dep: true, location: ../../libs/zmq-bus-config}
- {extra-dep: true, location: ../../libs/zmq-bus}
- {extra-dep: true, location: ../../libs/zmq-rpc}
- {location: ../../tools/batch/plugins/ws-connector}
- {location: ../../tools/batch/plugins/broker}
- {location: ../../libs/undo-redo}
- {location: ../../tools/batch/plugins/bus-logger}
- {location: ../../tools/batch/plugins/luna-empire}
- {location: ../../tools/batch/plugins/request-monitor}
- extra-dep: true
  location: {commit: 84691634169368214c99f8b56686b576f0423950, git: 'git@github.com:luna/luna.git'}
  subdirs: [core, passes, syntax/text/parser, syntax/text/lexer, stdlib, project]
- extra-dep: true
  location: {commit: 61ff909efd466735cd4820f9ab2c564e324b5546, git: 'git@github.com:luna/container.git'}
- extra-dep: true
  location: {commit: 4cc75aeb82ad2885427211a1be9cb0c7d9582c01, git: 'git@github.com:luna/data-pool.git'}
- extra-dep: true
  location: {commit: 6b1a30ae3ead794e3839d6552fd48a56b4447d24, git: 'git@github.com:luna/convert.git'}
- extra-dep: true
  location: {commit: a81f2eb37b0bddbc3391c8a29860b921aa94f3c8, git: 'git@github.com:luna/data-base.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'git@github.com:luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'git@github.com:luna/data-layer.git'}
- extra-dep: true
  location: {commit: 9da4c9b2534693cfe82adeb37f12eaadacb41e62, git: 'git@github.com:luna/data-repr.git'}
- extra-dep: true
  location: {commit: 89b0bb545ddde953c5692f234163748b9b4e84d2, git: 'git@github.com:luna/data-result.git'}
- extra-dep: true
  location: {commit: 8c3d63bb78c24fcfadd22efe1a0b8071c4240ff6, git: 'git@github.com:luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 1c6a4fd165e4b15cad114b0a554e0974fd119223, git: 'git@github.com:luna/functor-utils.git'}
- extra-dep: true
  location: {commit: 758f81a9914f46efa9137562b0a5ca3df9ce0661, git: 'git@github.com:luna/fuzzy-text.git'}
- extra-dep: true
  location: {commit: a1606cccc12cb521acbc598e52c481b9054b42a7, git: 'git@github.com:luna/impossible.git'}
- extra-dep: true
  location: {commit: 3ba7d5da78aab023fc74c44fc7445ffab0bc18e0, git: 'git@github.com:luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 965e23539a001517994398ae02421334bf77c6e6, git: 'git@github.com:luna/poly-control.git'}
- extra-dep: true
  location: {commit: e930d2854258a4160cf1b10dece72448e500c35e, git: 'git@github.com:luna/prologue.git'}
- extra-dep: true
  location: {commit: f4292663aea639c17f66ba3d67e09c79ebf62982, git: 'git@github.com:luna/type-cache.git'}
- extra-dep: true
  location: {commit: 107db9368e95e192d70c0dec274ecfe3592101d2, git: 'git@github.com:luna/typelevel.git'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'git@github.com:luna/data-prop.git'}
- extra-dep: true
  location: {commit: 4f5153aed4944317942ff9025c79f7fc3be85181, git: 'git@github.com:luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: f58214001b64d35f7502ec76bdc5410ba97032ff, git: 'git@github.com:luna/data-shell.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'git@github.com:luna/visualization-api.git'}
- extra-dep: true
  location: {commit: e63e373d67cd8dd7c179a618f5d32f6ffb3abdd3, git: 'git@github.com:luna/monoid'}
- extra-dep: true
  location: {commit: fe9834f3f5583086d76b12779a1c2a5290c72b0d, git: 'git@github.com:luna/text-processing'}
- extra-dep: true
  location: {commit: cbcd88c87e8888ebfeacd258cca96b3d6d489d35, git: 'git@github.com:luna/parsert'}
- extra-dep: true
  location: {commit: be6907da96975af1c5ca09555797a9891689cdb3, git: 'git@github.com:luna/vector-text'}
- extra-dep: true
  location: {commit: a7f6158465aaa9998fcb094d74906f608ce385c5, git: 'git@github.com:luna/terminal-text'}
- extra-dep: true
  location: {commit: c75acefee30d1c853da7e651c358d72b60386a07, git: 'git@github.com:luna/layouting'}
- extra-dep: true
  location: {commit: 7c7a6d657e7db8c3dcd80fbed0a7e02e02f43ae3, git: 'git@github.com:luna/monad-branch'}
