resolver: lts-12.16
ghc-options:
  '*': -threaded -fconstraint-solver-iterations=100 -O2 -fsimpl-tick-factor=200
local-bin-path:
  ../../dist/bin/private
apply-ghc-options: everything

# package-indices:
#   - name:            standard-hackage
#     download-prefix: https://hackage.haskell.org/package/
#     http: https://hackage.haskell.org/01-index.tar.gz

extra-deps:
- layered-state-1.1.4
- impossible-1.1.3
- typelevel-1.2.2
- container-1.1.5
- layouting-1.1.3
- monoid-0.1.8
- terminal-text-1.1.1
- lens-utils-1.4.5
- convert-1.5
- prologue-3.2.4
- vector-text-1.1.5
- monad-branch-1.0.3
- functor-utils-1.17.1

- c-storable-deriving-0.1.3
- unagi-chan-0.4.1.0
allow-newer: true

packages:
- {extra-dep: false, location: ../../libs/luna-empire}
- {extra-dep: true, location: ../../libs/batch/plugins/luna-empire}
- {extra-dep: true, location: ../../libs/batch/plugins/request-monitor}
- {extra-dep: true, location: ../../libs/luna-studio-common}
- {extra-dep: true, location: ../../libs/m-logger}
- {extra-dep: true, location: ../../libs/ws-connector}
- {extra-dep: true, location: ../../libs/zmq-bus-config}
- {extra-dep: true, location: ../../libs/zmq-bus}
- {extra-dep: true, location: ../../libs/zmq-rpc}
- {location: ../../tools/batch/plugins/ws-connector}
- {location: ../../tools/batch/plugins/broker}
- {location: ../../libs/undo-redo}
- {location: ../../tools/batch/plugins/bus-logger}
- {location: ../../tools/batch/plugins/luna-empire}
- {location: ../../tools/batch/plugins/request-monitor}
- extra-dep: true
  location: {commit: 650c7ef5b53ea1733b9ecb0b59f91d09e4c8e167, git: 'git@github.com:luna/luna.git'}
  subdirs:
    - core
    - syntax/text/parser
    - syntax/text/builder
    - syntax/text/lexer
    - syntax/text/model
    - syntax/text/prettyprint
    - debug
    - passes
    - package
    - runtime
    - stdlib
    - lib/autovector
    - lib/cpp-containers
    - lib/data-construction
    - lib/data-tag
    - lib/data-typemap
    - lib/data-property
    - lib/data-storable
    - lib/exception
    - lib/foreign-utils
    - lib/future
    - lib/generic-traversable
    - lib/memory-manager
    - lib/memory-pool
    - lib/nested-containers
    - lib/parser-utils
    - lib/syntax-definition
    - lib/text-processing
    - lib/th-builder
    - lib/tuple-utils
    - lib/type-cache
    - lib/typelevel
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'git@github.com:luna/visualization-api.git'}
- extra-dep: true
  location: {commit: 1fe94d4d8b106b2ab37c65de9200b3f0404ac2ca, git: 'git@github.com:luna/fuzzy-text.git'}
