resolver: nbo.yaml
ghc-options:
  $locals: -threaded -O2
  $everything: -fconstraint-solver-iterations=100 -O2
  matrix: -O0 # https://github.com/Daniel-Diaz/matrix/issues/43
local-bin-path:
  ../../dist/bin/private

packages:
- ../../libs/batch/plugins/luna-empire
- ../../libs/batch/plugins/request-monitor
- ../../libs/luna-empire
- ../../libs/luna-studio-common
- ../../libs/m-logger
- ../../libs/undo-redo
- ../../libs/ws-connector
- ../../libs/zmq-bus
- ../../libs/zmq-bus-config
- ../../libs/zmq-rpc
- ../../tools/batch/plugins/broker
- ../../tools/batch/plugins/bus-logger
- ../../tools/batch/plugins/luna-empire
- ../../tools/batch/plugins/request-monitor
- ../../tools/batch/plugins/ws-connector
