name:    luna-ws-connector
version: 0.1.0.0
license: AGPL-3
author:  Luna Team <contact@luna-lang.org>

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - Strict
  - StrictData

executables:
  luna-ws-connector:
    source-dirs: src-app
    ghc-options: -Wall -O2 -threaded
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - either
      - ekg
      - luna-bus
      - luna-ws-connector
      - m-logger
      - mtl
      - prologue
      - zeromq4-haskell
      - optparse-applicative

library:
  source-dirs: src
  ghc-options: -Wall -O2 -threaded
  dependencies:
    - async
    - base
    - base64-bytestring
    - binary
    - bytestring
    - either
    - exceptions
    - luna-bus
    - m-logger
    - random
    - mtl
    - prologue
    - text
    - unagi-chan
    - websockets
    - zeromq4-haskell

