name:    luna-ws-connector
version: 0.1.0.0
license: AGPL-3
author:  Luna Team <contact@luna-lang.org>

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - Arrows
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - LiberalTypeSynonyms
  - MonadComprehensions
  - MultiWayIf
  - MultiParamTypeClasses
  - NamedWildCards
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - QuasiQuotes
  - RankNTypes
  - RecursiveDo
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeSynonymInstances
  - TypeOperators
  - ViewPatterns

executables:
  luna-ws-connector:
    source-dirs: src-app
    ghc-options: -Wall -O2 -threaded
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - either
      - ekg
      - luna-bus
      - luna-ws-connector
      - m-logger
      - mtl
      - prologue
      - zeromq4-haskell
      - optparse-applicative

library:
  source-dirs: src
  ghc-options: -Wall -O2 -threaded
  dependencies:
    - aeson
    - async
    - base
    - base64-bytestring
    - binary
    - bytestring
    - either
    - exceptions
    - lens-utils
    - luna-bus
    - luna-configurator
    - luna-exception
    - m-logger
    - mtl
    - prologue
    - random
    - text
    - unagi-chan
    - websockets
    - yaml
    - zeromq4-haskell
