resolver:
  name: nbo-gui-20160520
  location: https://bitbucket.org/NewByteOrder/stack-snapshots/raw/master/nbo-gui-20160520.yaml
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160517_ghc-7.10.3:
        url: "https://s3-eu-west-1.amazonaws.com/nbo-toolchain/ghcjs/ghcjs-0.2.0.20160517-dupa.tar.gz"
ghc-options:
  nodelab: -DGHCJS_BROWSER
extra-deps:
  - datetime-0.3.1
  - placeholders-0.1
packages:
  - .
  - location: ../libs/luna-empire-api
    extra-dep: true
  - location: ../libs/luna-empire-api-json
    extra-dep: true
  - location: ../libs/scope-searcher
    extra-dep: true
  - location:
      git: https://github.com/luna/container.git
      commit: cd137cdfa6059cc267aa865d78bbbf0a17a4c657
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-repr.git
      commit: a725e4dad9b0916514662e917cef692a91a51029
    extra-dep: true
  - location:
      git: https://github.com/luna/hsprocessing.git
      commit: b96747cf0c3a4362b4d5827eb567be85c2d1dd13
    extra-dep: true
  - location:
      git: https://github.com/luna/prologue.git
      # commit: 9ba882921b6e2527923bbb0f9ba54c41b43a8135  # 1.0.6
      commit: 48c846701e796d28734f96524ba1e0b36cce57c0  # 1.0.2
    extra-dep: true
  - location:
      hg: https://remdezx@bitbucket.org/remdezx/react-flux
      commit: e966c11fb6d898ac3085074791a51ad1788241da
    extra-dep: true
  - location:
      hg: https://remdezx@bitbucket.org/remdezx/react-flux
      commit: e966c11fb6d898ac3085074791a51ad1788241da
    extra-dep: true
  - location:
      git: 'https://bitbucket.org/NewByteOrder/visualization-api.git'
      commit: af5a618f5813ac639a6760836a6d6fa7ef5af1da
    extra-dep: true
