resolver: lts-7.2
compiler: ghcjs-0.2.1.9007002_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007002_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-10-01-lts-7.2-9007002.tar.gz
          sha1: a41ae415328e2b257d40724d13d1386390c26322

ghc-options:
  nodelab: -DGHCJS_BROWSER
extra-deps:
  # - datetime-0.3.1
  # - loop-0.3.0
  # - matrix-0.3.5.0
  # - placeholders-0.1

packages:
  - .
  - location: ../libs/luna-empire-api
    extra-dep: true
  - location: ../libs/luna-empire-api-json
    extra-dep: true
  - location: ../libs/scope-searcher
    extra-dep: true
  - location:
      git: https://github.com/luna/container.git
      commit: cd137cdfa6059cc267aa865d78bbbf0a17a4c657
    extra-dep: true
  - location:
      git:    https://github.com/luna/data-repr.git
      commit: a725e4dad9b0916514662e917cef692a91a51029
    extra-dep: true
  - location:
      git: https://github.com/luna/hsprocessing.git
      commit: b96747cf0c3a4362b4d5827eb567be85c2d1dd13
    extra-dep: true
  - location:
      git: https://github.com/luna/prologue.git
      # commit: 9ba882921b6e2527923bbb0f9ba54c41b43a8135  # 1.0.6
      commit: 48c846701e796d28734f96524ba1e0b36cce57c0  # 1.0.2
    extra-dep: true
  - location:
      hg: https://remdezx@bitbucket.org/remdezx/react-flux
      commit: 3e5b45e70415a5f8ea6aea547f5dadfe717ee78e
    extra-dep: true
  - location:
      git: 'https://bitbucket.org/NewByteOrder/visualization-api.git'
      commit: ddfcd1e0372b93e947b380b911c123fe67227b21
    extra-dep: true
